[package]
name = "fedimint-bitcoind"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "Bitcoin Core connectivity used by Fedimint"
license = "MIT"
readme = "../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[features]
default = ["bitcoincore-rpc", "esplora-client"]

[lib]
name = "fedimint_bitcoind"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true, optional = true }
esplora-client = { workspace = true, optional = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
hex = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
