[package]
name = "fedimintd"
version = { workspace = true }
authors = ["The Fedimint Developers"]
edition = "2021"
description = "fedimintd is the main consensus code for processing transactions and REST API"
license = "MIT"
readme = "../README.md"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[features]
telemetry = ["fedimint-logging/telemetry"]
default = ["telemetry"]

[[bin]]
name = "fedimintd"
path = "src/bin/main.rs"

[lib]
name = "fedimintd"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }

# setup dependencies
axum = { workspace = true }
bincode = { workspace = true }
bitcoin = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
console-subscriber = "0.4.0"
fedimint-aead = { workspace = true }
fedimint-bitcoind = { workspace = true }
fedimint-core = { workspace = true }
fedimint-ln-common = { workspace = true }
fedimint-ln-server = { workspace = true }
fedimint-lnv2-common = { workspace = true }
fedimint-lnv2-server = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-meta-server = { workspace = true }
fedimint-metrics = { workspace = true }
fedimint-mint-server = { workspace = true }
fedimint-rocksdb = { workspace = true }
fedimint-server = { workspace = true }
fedimint-unknown-common = { workspace = true }
fedimint-unknown-server = { workspace = true }
fedimint-wallet-server = { workspace = true }
futures = { workspace = true }
http = "1.1"
http-body = "1.0"
hyper = { workspace = true, features = ["full"] }
itertools = { workspace = true }
jsonrpsee = { version = "0.24.3", features = ["server"] }
rand = { workspace = true }
rcgen = "0.13.1"
ring = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha3 = { workspace = true }
tbs = { workspace = true }
thiserror = { workspace = true }
threshold_crypto = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tokio-util = { version = "0.7.11", features = ["codec"] }
tower = { version = "0.4", features = ["util"] }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }

[build-dependencies]
fedimint-build = { workspace = true }
